version: 2

sources:
  - name: staging
    database: de-zoomcamp-376514
    schema: trips_data_all

    tables: 
      - name: green_tripdata
      - name: yellow_tripdata
      - name: fhv_tripdata

models:
  - name: stg_green_trip_data
    description: >
      Trip made by green taxi
    columns:
      - name: tripid
        description: Primary key for this table
        tests:
            - unique:
                severity: warn
            - not_null:
                severity: warn
      - name: VendorId
        description: >
            A code by provider
            1 = Creative Mobile Technologies, LLC;
            2 = Venifone Inc.
      - name: pickup_locationid
        description: locationid where the meter was engaged.
        tests:
          - relationships:
              to: ref('taxi_zone_lookup')
              field: locationid
      - name: dropoff_locationid
        description: location where the meter was engaged.
        tests:
          - relationships:
              to: ref('taxi_zone_lookup')
              field: locationid
      - name: payment_type
        description: >
          A numeric code signifying how the passenger paid the trip.
        tests:
          - accepted_values:
              values: "{{ var('payment_type_values') }}"
              severity: warn
              quote: false
  - name: stg_yellow_trip_data
    description: >
      Trip made by yellow taxi
    columns:
      - name: tripid
        description: Primary key for this table
        tests:
            - unique:
                severity: warn
            - not_null:
                severity: warn
      - name: VendorId
        description: >
            A code by provider
            1 = Creative Mobile Technologies, LLC;
            2 = Venifone Inc.
      - name: pickup_locationid
        description: locationid where the meter was engaged.
        tests:
          - relationships:
              to: ref('taxi_zone_lookup')
              field: locationid
      - name: dropoff_locationid
        description: location where the meter was engaged.
        tests:
          - relationships:
              to: ref('taxi_zone_lookup')
              field: locationid
      - name: payment_type
        description: >
          A numeric code signifying how the passenger paid the trip.
        tests:
          - accepted_values:
              values: "{{ var('payment_type_values') }}"
              severity: warn
              quote: false